addr: '0.0.0.0'

# run on port
port: 4567

# directory to store data JSON
path: 'data'

# directory to store guard JSON ( data validators/config )
guard: 'guard'

# directory to store JSON templates
templates: 'templates'

# directory to store apps
apps: 'public/apps'

# directory to store tmp files
tmp: 'tmp'

# accept requests from
allow_origin: 'http://localhost:4567'

# url to sparql endpoint
sparql: 'http://localhost:4321/ds'

# baseurl of deployment
# uncomment this and set if deployment environment is behind a proxy
#base_url: 'http://www.perseids.org/jackson'

# uri prefix for data object urns
#uri_prefix: 'http://www.perseids.org/jackson'

# debug output
debug: false 
