addr: '0.0.0.0'

# run on port
port: 4567

# directory to store data JSON
path: 'data'

# directory to store guard JSON ( data validators/config )
guard: 'guard'

# directory to store JSON templates
templates: 'templates'

# directory to store apps
apps: 'public/apps'

# directory to store tmp files
tmp: 'tmp'

# accept requests from
allow_origin: [ 'http://localhost:4567' ]

# url to sparql endpoint
sparql: 'http://localhost:4321/ds'

# debug output
debug: false 
