path: 'data'
templates: 'templates'
apps: 'public/apps'
tmp: 'tmp'
port: 4567
host: 'http://localhost:4567'
cors: [ 'http://localhost:4567', 'http://localhost:3000' ]
sparql: 'http://localhost:4321/ds'
family: []
debug: false
urn: "http://github.com/caesarfeta/JackSON/blob/master/docs/SCHEMA.md#urn"
src: "http://github.com/caesarfeta/JackSON/blob/master/docs/SCHEMA.md#src"